### ISSUE TITLE
NPE when starting up in environment without configuration

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#16]
_Original author: ipolevoy@gmail.com (May 04, 2011 17:49:00)_

If ACTIVE_ENV is set to a value without equivalent in DbConfig, there is an NPE:

activeweb.InitException: failed to create a new instance of class: app.config.AppBootstrap: class java.lang.NullPointerException:null

```
    at java.util.Hashtable.put(Hashtable.java:394)

    at java.util.Properties.setProperty(Properties.java:143)

    at app.config.DbConfig.getTestingProperties(DbConfig.java:38)

    at app.config.DbConfig.init(DbConfig.java:17)

    at app.config.AppBootstrap.init(AppBootstrap.java:18)

    Truncated. see log file for complete stacktrace
```

Caused By: java.lang.NullPointerException

```
    at java.util.Hashtable.put(Hashtable.java:394)

    at java.util.Properties.setProperty(Properties.java:143)

    at app.config.DbConfig.getTestingProperties(DbConfig.java:38)

    at app.config.DbConfig.init(DbConfig.java:17)

    at app.config.AppBootstrap.init(AppBootstrap.java:18)

    Truncated. see log file for complete stacktrace
```

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=16_

**Comment by ipolevoy** [comment]
irrelevant, we are getting a proper exception and a message now.
