### ISSUE TITLE
StringIndexOutOfBoundsException in case of incorrect route 

### ISSUE THREAD

**Issue by ipolevoy** [javalite/activeweb#177]
To reproduce: 

execute this:

`curl -X POST -H "Content-Type: octet/stream" --data-binary @src/test/resources/people.json http://localhost:8080`

against activeweb-rest project

```
[qtp425107133-16] ERROR org.javalite.activeweb.RequestDispatcher - ActiveWeb ERROR: 
Request URL: http://localhost:8080/
ContextPath: 
Query String: null
URI Full Path: /
URI Path: /
Method: POST

java.lang.StringIndexOutOfBoundsException: String index out of range: -6
    at java.lang.String.substring(String.java:1918)
    at org.javalite.activeweb.Router.matchStandard(Router.java:123)
    at org.javalite.activeweb.Router.recognize(Router.java:86)
    at org.javalite.activeweb.RequestDispatcher.doFilter(RequestDispatcher.java:185)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1645)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:564)
```

**Comment by ipolevoy** [comment]
too old to fix
