### ISSUE TITLE
Adding a non-ActiveWeb annotation on action method causes IllegalArgumentException 

### ISSUE THREAD

**Issue by ipolevoy** [javalite/activeweb#193]
```
java.lang.IllegalArgumentException: No enum constant org.javalite.activeweb.HttpMethod.Protected
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.javalite.activeweb.HttpMethod.valueOf(HttpMethod.java:26)
	at org.javalite.activeweb.AppController.standardActionSupportsHttpMethod(AppController.java:235)
	at org.javalite.activeweb.AppController.actionSupportsHttpMethod(AppController.java:219)
	at org.javalite.activeweb.ControllerRunner.checkActionMethod(ControllerRunner.java:189)
	at org.javalite.activeweb.ControllerRunner.run(ControllerRunner.java:55)
	at org.javalite.activeweb.RequestDispatcher.doFilter(RequestDispatcher.java:192)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)

```

**Comment by Doublefinger** [comment]
I encountered this problem when I try to restrict access on method through annotation. Is there any other approach? I can add another controller, but it would be strange.

**Comment by ipolevoy** [comment]
@Doublefinger, we should just fix it, stay tuned

**Comment by Doublefinger** [comment]
@ipolevoy Sounds great! Appreciate~

**Comment by ipolevoy** [comment]
fixed, grab a latest snapshot:  http://repo.javalite.io/org/javalite/activeweb/1.14-SNAPSHOT/

**Comment by ccarvalho-paywithmybank** [comment]
Hey, any idea on when 1.14 will become a final release?

**Comment by ipolevoy** [comment]
@ccarvalho-paywithmybank we are planning to make a new release this weekend, stay tuned

**Comment by ccarvalho-paywithmybank** [comment]
Hi @ipolevoy ! Any updates? Looking forward for this new version  :)

**Comment by ipolevoy** [comment]
@ccarvalho-paywithmybank actually, yes. The ActiveWeb abd ActiveJDBC haev both been released:
http://search.maven.org/#search%7Cga%7C1%7Cactiveweb
http://search.maven.org/#search%7Cga%7C1%7Cactivejdbc

We will be updating site info, but you can switch to fixed versions.
