### ISSUE TITLE
jboss StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kolshi** [javalite/activeweb#204]
20:02:43,710 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (MSC service thread 1-15) Exception starting filter dispatcher: java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -7

**Comment by kolshi** [comment]
20:14:21,851 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/]] (MSC service thread 1-16) Exception starting filter dispatcher: java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at org.javalite.activeweb.ControllerPackageLocator.addClassesUrl(ControllerPackageLocator.java:135) [activeweb-1.10.jar:]
	at org.javalite.activeweb.ControllerPackageLocator.hackForWeblogic(ControllerPackageLocator.java:118) [activeweb-1.10.jar:]
	at org.javalite.activeweb.ControllerPackageLocator.getUrls(ControllerPackageLocator.java:102) [activeweb-1.10.jar:]
	at org.javalite.activeweb.ControllerPackageLocator.locateControllerPackages(ControllerPackageLocator.java:45) [activeweb-1.10.jar:]
	at org.javalite.activeweb.ControllerRegistry.<init>(ControllerRegistry.java:48) [activeweb-1.10.jar:]
	at org.javalite.activeweb.RequestDispatcher.init(RequestDispatcher.java:49) [activeweb-1.10.jar:]
	at cn.yuuji.web.servlet.CombinedFilter.init(CombinedFilter.java:27) [classes:]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:447) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:3269) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3865) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_71]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at java.lang.String.substring(String.java:1911) [rt.jar:1.7.0_71]
	at org.javalite.activeweb.ControllerPackageLocator.addClassesUrl(ControllerPackageLocator.java:132) [activeweb-1.10.jar:]
	... 15 more

**Comment by kolshi** [comment]
JBoss AS 7.1.1.Final

14:41:12,759 INFO  [stdout] (MSC service thread 1-9) [/WEB-INF/classes/activeweb.properties, /WEB-INF/classes/activejdbc_models.properties, /WEB-INF/classes/i18n/, /WEB-INF/classes/cn/, /WEB-INF/classes/app/]

**Comment by kolshi** [comment]
for (String str : filterConfig.getServletContext().getResourcePaths("/WEB-INF/classes/")) {
            System.out.println("\t\t-----------\t\t" + str);
        }



14:41:12,254 INFO  [stdout] (MSC service thread 1-9) 		-----------		/WEB-INF/classes/activeweb.properties
14:41:12,254 INFO  [stdout] (MSC service thread 1-9) 		-----------		/WEB-INF/classes/activejdbc_models.properties
14:41:12,254 INFO  [stdout] (MSC service thread 1-9) 		-----------		/WEB-INF/classes/i18n/
14:41:12,254 INFO  [stdout] (MSC service thread 1-9) 		-----------		/WEB-INF/classes/cn/
14:41:12,255 INFO  [stdout] (MSC service thread 1-9) 		-----------		/WEB-INF/classes/app/

**Comment by kolshi** [comment]
@ipolevoy

**Comment by ipolevoy** [comment]
are you trying to say there is an issue on JBoss?
I like your very descriptive comments :)

**Comment by ericbn** [comment]
Looks like error came from `ControllerPackageLocator.addClassesUrl()`, from this line:

    String url = urlString.substring(urlString.indexOf(":") + 2, urlString.indexOf("!"));

**Comment by ipolevoy** [comment]
I have not tested AW  on JBoss in ages. Last time deployed there in 2010.  Shall we try? Looks like @kolshi is using JBoss AS 7.1.1.Final

**Comment by kolshi** [comment]
@ipolevoy is using JBoss AS 7.1.1.Final   deploy   war

**Comment by ipolevoy** [comment]
@kolshi, I'm not too familiar with JBoss. Can  you please provide instructions for deployment? That is, where to drop the file and what URL to access  - this is to save our time

**Comment by kolshi** [comment]
http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.tar.gz
Install to /opt/jboss
git clone https://git.oschina.net/yuuji/sprouts.git
cd sprouts
./deploy/bin/jboss.sh start

**Comment by ipolevoy** [comment]
this is fixed. Grab latest snapshot from: http://repo.javalite.io/, 
ActiveWeb version: 1.11-SNAPSHOT. 
ActiveJDBC version: 1.4.10-SNAPSHOT

**Comment by kolshi** [comment]
Thank you very much

**Comment by ipolevoy** [comment]
Enjoy
