### ISSUE TITLE
long polling

### ISSUE THREAD

**Issue by codezion** [javalite/activeweb#241]
Can not find support for long polling nor easy way to implement it. HTTP response and answer seems to be in Context, but Context is not accessible by controller. Is long polling coming into framework or is it something to be implemented as separate servlet?

Maybe just add a way to call startAsync(). Then the following examples should be possible.

http://peter-braun.org/2013/04/asynchronous-processing-from-servlet-3-0-to-jax-rs-2-0/
http://stackoverflow.com/questions/8081895/implementing-long-polling-in-an-asynchronous-fashion

**Comment by ipolevoy** [comment]
I think this is a better explanation: https://plumbr.eu/blog/java/how-to-use-asynchronous-servlets-to-improve-performance. 
However, the async API in Servlets 3 is quite dependent on .. Servlet API. ActiveWeb is implemented as a Servlet Filter, not a servlet so it will be somewhat difficult to bake it in. On the other hand, you can easily create a separate servlet based on Servlet 3 API and add that to `web.xml`. With ActiveWeb it is easy to mix and match different frameworks in the same application. In most of our projects requests are  are based on database pools, so using async calls will not buy any performance.

**Comment by ipolevoy** [comment]
Also, the Servlet API  is completely hidden under  ActiveWeb for the purpose of providing the same features in an easy form. Exposing Servlet 3 API on top of ActiveWeb API will mean violating this principle. If there are more requests come for this, we will put this on the table.

**Comment by codezion** [comment]
Thanks for your explanation. That way needs some thinking on how to authenticate and authorize because all that is now implemented on the framework side. Also DB connections need to be figured out. It is like creating some amount of duplicate framework to get that working, but it may be so in any case. Maybe pushing that DB and authentication info through session to the new servlet. I will try.

Long poll demo behind the link above works, but not with the ActiveWeb because of the filter problems. Filter is now "/*" and it is like in your example. Could you figure out some way to get routing working to the new servlet? 
like /longpoll -> to longpoll servlet and all the rest /* -> to the AvtiveWeb framework.

Filter for org.javalite.activeweb.RequestDispatcher  takes all http queries and ignores /longpoll because of no controller with that name. If I add longpoll as part of exclusions, i got null pointer. Some reason null pointer do not happen for these: css,images,html,js,ico,png (btw. I think example should be updated like: .css,/images,.html,.js,.ico,.png).

So exclusions: longpoll,css,images,html,js,ico,png causes this (version 1.13):

(questDispatcher) - ActiveWeb internal error: java.lang.NullPointerException
        at org.javalite.activeweb.RequestDispatcher.getRequestProperties(RequestDispatcher.java:310)
        at org.javalite.activeweb.RequestDispatcher.renderSystemError(RequestDispatcher.java:268)
        at org.javalite.activeweb.RequestDispatcher.doFilter(RequestDispatcher.java:222)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
        at java.lang.Thread.run(Thread.java:744)

**Comment by codezion** [comment]
I have /mysite in development system and /xxx/mysite in production system. I tried to find a workaround to get extra servlet working with AvtiveWeb but can not figure way to configure that. I tied:

/main/mysite Do not work because of there is no controller mainController (there is mysiteController tho). And I don't even like that way because of in production it will be /xxx/main/mysite. So ActiveWeb wants to be in the root.

With what ever path the new servlet do not get connections because of ActiveWeb say not that controller and gives 404 to user

**Comment by ipolevoy** [comment]
@codezion, you can simply add longpoll to the web.xml file: https://github.com/javalite/activeweb-simple/blob/master/src/main/webapp/WEB-INF/web.xml#L18

See the "exclusions" property? This way, ActiveWeb filter will completely ignore your longpoll call URL. 

A second way of doing the same is to ignore URLs with regular expressions in your RouteConfig class. See this method: 
https://github.com/javalite/activeweb/blob/master/activeweb/src/main/java/org/javalite/activeweb/AbstractRouteConfig.java#L40

I hope it helps

tx

**Comment by ipolevoy** [comment]
@codezion , actually this has already been documented: http://localhost:8080/routing#excluding-some-routes

**Comment by codezion** [comment]
Thank you for more info. I tried that first way. It do not work in this case because of null pointer error. The second one needs more study to understand how to use it and where it should be.

I just got it working by creating my own filter that steal the query and sends it to longpoll servlet before it enters to ActiveWeb filter, so it is completely isolated from the framework request path now.

**Comment by ipolevoy** [comment]
@codezion you can do it that way too. I think that Servlet Filters are invoked in the same order as they are defined in `web.xml`. If you declare yours above `RequestDispatcher`, it will be invoked first.

**Comment by ipolevoy** [comment]
closing, too old, migrated this repo to https://github.com/javalite/javalite
