### ISSUE TITLE
Tests failed after ActiveWeb upgrade from 1.13 to 1.14-SNAPSHOT

### ISSUE THREAD

**Issue by yanchevsky** [javalite/activeweb#246]
java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1075)
	at org.hornetq.core.server.impl.FileLockNodeManager.tryLock(FileLockNodeManager.java:266)
	at org.hornetq.core.server.impl.FileLockNodeManager.isBackupLive(FileLockNodeManager.java:82)
	at org.hornetq.core.server.impl.HornetQServerImpl$SharedStoreLiveActivation.run(HornetQServerImpl.java:2186)
	at org.hornetq.core.server.impl.HornetQServerImpl.start(HornetQServerImpl.java:451)
	at org.hornetq.jms.server.impl.JMSServerManagerImpl.start(JMSServerManagerImpl.java:488)
	at org.hornetq.jms.server.embedded.EmbeddedJMS.start(EmbeddedJMS.java:115)
	at org.javalite.hornet_nest.HornetNest.<init>(HornetNest.java:110)

**Comment by ipolevoy** [comment]
In reality, the HornetQ does not throw an exception from its start() method, but rather fails to work!
We will improve messaging in our exception

**Comment by ipolevoy** [comment]
In reality, this was due to not using setInjector methods in tests. Since https://github.com/javalite/activeweb/issues/239, the test must set their injector and not rely on whatever is in AppBootstrap.
