### ISSUE TITLE
RouteConfig routes ordering issue

### ISSUE THREAD

**Issue by SpokeU** [javalite/activeweb#248]
Say you have custom RouteConfig and two routes there
1.route("/projects/new_form").get().to(ProjectsController.class).action("newForm");
2.route("/projects/{id}").get().to(ProjectsController.class).action("view");

This is ok, but as soon as you place route 2 before route 1, you'll no longer be able to go to new_form route because it tries to match it to first route {id} param and throws java.lang.NumberFormatException: For input string: "new_form".

**Comment by ipolevoy** [comment]
@SpokeU , routes are triggered in the same order as they are specified. Since the second route you have will match the first one, there is no point in redordering them, as this : 

```java
route("/projects/{id}").get().to(ProjectsController.class).action("view");
```

will match `/projects/anything`. 

Additionally, I tried to recreate your issue with  `NumberFormatException`, and was unable to do so. ActiveWeb does not interpret IDs as numbers or any other type. This exception must have come from your code. Can you provide a full exception stack? 

Here is the branch with my test: https://github.com/javalite/activeweb/commit/29576dd7ad5c2421febf4d54eaf19035faeadd16

Closing, as a non-issue. If we need to, we can re-open

**Comment by ipolevoy** [comment]
Additionally, I suggest to write routes like this: 

```java
route("/projects/{id}").to(ProjectsController.class).action("view").get();
```

It just sounds better:)

**Comment by SpokeU** [comment]
Wow thats a quick response)
Here is stack trace 
java.lang.NumberFormatException: For input string: "new_form"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at app.controllers.ProjectsController.view(ProjectsController.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.javalite.activeweb.ControllerRunner.executeAction(ControllerRunner.java:289)
	at org.javalite.activeweb.ControllerRunner.run(ControllerRunner.java:65)
	at org.javalite.activeweb.RequestDispatcher.doFilter(RequestDispatcher.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ipolevoy** [comment]
haha, no guarantees of this speed next time :)

Here is your problem: 

```java
at app.controllers.ProjectsController.view(ProjectsController.java:34)
```
