### ISSUE TITLE
StringIndexOutOfBoundsException when parsing a route

### ISSUE THREAD

**Issue by ipolevoy** [javalite/activeweb#367]
```
at java.lang.String.substring(String.java:1931)
at org.javalite.activeweb.Router.matchStandard(Router.java:128)
at org.javalite.activeweb.Router.recognize(Router.java:86)
at org.javalite.activeweb.RequestDispatcher.doFilter(RequestDispatcher.java:193)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)

```

**Comment by ipolevoy** [comment]
masking an exception is not "fixing" an issue :(

**Comment by ipolevoy** [comment]
this was reproduced by a Curl request: 

     curl -X HEAD http://localhost:8080/

against activeweb-simple project
