### ISSUE TITLE
Error in routing

### ISSUE THREAD

**Issue by alniks** [javalite/activeweb#399]
After recent update we got an exception during activeweb routing:

`Index: 1, Size: 1","stacktrace":"java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:657)
    at java.util.ArrayList.get(ArrayList.java:433)
    at org.javalite.activeweb.RouteBuilder.matches(RouteBuilder.java:251)
    at org.javalite.activeweb.Router.matchCustom(Router.java:98)
    at org.javalite.activeweb.Router.recognize(Router.java:70)
    at org.javalite.activeweb.RequestDispatcher.doFilter(RequestDispatcher.java:191)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)`

The routing configured as follows (no routing  for POST):

`
route("/sub/messages/{id}").to(MessagesController.class).action("single").get();
route("/sub/messages").to(MessagesController.class).action("multiple").get();
`

The controller:

`
package app.controllers.sub;

public class MessagesController extends AppController {

   @POST
    public void index() {
    }

   public void multiple() {
   }

  public void single() {
  }
}
`

curl:

`
curl -X POST -H "Content-type: application/json" -d \
'{
    "id": 2917,
    "text": "Test Test 08/17" 
}' 'http://localhost/sub/messages'
`

**Comment by ipolevoy** [comment]
@alniks I was unable to reproduce this issue. Please, see this branch: https://github.com/javalite/activeweb-simple/tree/issue399

When calling your Curl command, I get this output: 

![selection_001517](https://user-images.githubusercontent.com/500941/45909168-f87dc880-bdc5-11e8-9d5f-e6ecf9526e46.png)

**Comment by alniks** [comment]
@ipolevoy, The problem was not in different POST and GET methods. Here is the failing configuration:

`package app.controllers.api;

import org.javalite.activeweb.AppController;
import org.javalite.activeweb.annotations.POST;

/**
 *
 * @author alex
 */
public class TestController extends AppController {
    
    @POST
    public void index() {
        respond("index");
    }
    
}`

`package app.controllers.api;

import org.javalite.activeweb.AppController;

/**
 *
 * @author alex
 */
public class ApiHomeController extends AppController {

    public void index() {
        respond("home");
    }
    
}`

`package app.config;


import app.controllers.api.ApiHomeController;
import org.javalite.activeweb.AbstractRouteConfig;
import org.javalite.activeweb.AppContext;

/**
 * @author alex
 */
public class RouteConfig extends AbstractRouteConfig {

    @Override
    public void init(AppContext appContext) {
        route("/api").to(ApiHomeController.class).action("index").get();
    }
}`

**Comment by ipolevoy** [comment]
@alniks I was able to reproduce the issue
