### ISSUE TITLE
NPE in @link_to tag if current controller not exists

### ISSUE THREAD

**Issue by yanchevsky** [javalite/activeweb#420]
Conditions:
1. Send request to non-existent controller.
2 Error template should contains @link_to tag without parameter "controller", something like <@link_to title="Home">Home</@link_to>

```
Rendering template: '/system/404.ftl' without layout. 
ActiveWeb internal error: 
org.javalite.activeweb.ViewException: java.lang.NullPointerException; null
	at org.javalite.activeweb.freemarker.FreeMarkerTag.execute(FreeMarkerTag.java:61)
......................
Caused by: java.lang.NullPointerException
	at org.javalite.activeweb.freemarker.LinkToTag.render(LinkToTag.java:190)
	at org.javalite.activeweb.freemarker.FreeMarkerTag.execute(FreeMarkerTag.java:57)


```

**Comment by ipolevoy** [comment]
@yanchevsky how is it possible for controller to not exist?
