### ISSUE TITLE
CSRFFilter not supported multipart/form-data

### ISSUE THREAD

**Issue by yanchevsky** [javalite/activeweb#426]
Filter should be check submitted content for the token.

**Comment by yanchevsky** [comment]
```
org.javalite.activeweb.ControllerException: this is not a multipart request, be sure to add this attribute to the form: ... enctype="multipart/form-data" ...
at org.javalite.activeweb.HttpSupport.multipartFormItems(HttpSupport.java:842)
at org.javalite.activeweb.HttpSupport.multipartFormItems(HttpSupport.java:795)
at org.javalite.activeweb.controller_filters.CSRFFilter.verify(CSRFFilter.java:33)
at org.javalite.activeweb.controller_filters.CSRFFilter.before(CSRFFilter.java:19)
at org.javalite.activeweb.ControllerRunner.filterBefore(ControllerRunner.java:255)
at org.javalite.activeweb.ControllerRunner.run(ControllerRunner.java:51)
at org.javalite.activeweb.RequestDispatcher.doFilter(RequestDispatcher.java:207)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at de.javakaffee.web.msm.RequestTrackingContextValve.invoke(RequestTrackingContextValve.java:99)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:158)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by yanchevsky** [comment]
Problems with file uploading detected  with active CSRF protection.
